import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>

        <header>
            <h1 className="text-center tracking-tight">
              <span className="text-2xl font-extrabold uppercase">Two Truths</span><br/>
              <span className="text-4xl">Library</span>
            </h1>            
          </header>

        {children}
      </body>
    </html>
  );
}
